name: doc-chat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - openai==0.28.0
    - streamlit==1.25.0
    - PyPDF2==3.0.1
    - python-docx==0.8.11
    - pymupdf==1.22.5   # For faster PDF extraction
    - joblib==1.3.2
    - docx2txt==0.8
    - sentence-transformers==2.2.2
    - faiss-cpu==1.7.4
    - huggingface-hub==0.11.1
    - torch==2.0.1
    - torchvision==0.15.2
    - torchaudio==2.0.2
